In [59]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.impute import KNNImputer
from sklearn.compose import ColumnTransformer

from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression, LinearRegression

In [9]:
Data = pd.read_csv('mixed_missing_data.csv')
Data.head(2)

,age,bmi,cholesterol,glucose,systolic_bp,income,gender,smoking_status,blood_group,exercise_level,diet_type,region
0,58.0,27.8,183.9,84.7,120.7,41971.27,Male,Non-Smoker,B+,NaN,NaN,Rural
1,71.0,26.3,NaN,108.4,102.4,56746.16,NaN,Former Smoker,O-,High,NaN,Urban

In [116]:
Data[['age']].boxplot()

In [10]:
X = Data.drop(columns = ['income',	'gender',	'smoking_status',	'blood_group',	'exercise_level',	'diet_type',	'region'])
X

     age   bmi  cholesterol  glucose  systolic_bp
0   58.0  27.8        183.9     84.7        120.7
1   71.0  26.3          NaN    108.4        102.4
2   48.0  20.0        212.8     73.8        126.7
3   34.0  28.9        125.9     60.2         98.1
4   62.0  22.6        214.5     82.8        124.3
..   ...   ...          ...      ...          ...
95  35.0  26.3        184.7    101.2        138.2
96  64.0  24.3        236.3     71.2        123.0
97  37.0  29.4        195.5     92.3        120.7
98  66.0  28.9        188.8    117.7        144.2
99  72.0  22.2        161.3     95.3        139.1

[100 rows x 5 columns]

In [11]:
Y = Data['smoking_status']

In [27]:
df = X.sample(6)
df

     age   bmi  cholesterol  glucose  systolic_bp
79   NaN  30.3        214.0     94.0        108.3
58  21.0  26.5        209.8    109.0        122.1
5   27.0  23.9        227.8    116.8        117.2
19  72.0  22.9        168.1     94.7          NaN
93  59.0   NaN        143.6    109.9        110.2
25  21.0  30.3          NaN     90.0         83.1

In [28]:
df.isnull().sum()

age            1
bmi            1
cholesterol    1
glucose        0
systolic_bp    1
dtype: int64

In [31]:
df1 = pd.DataFrame()

df1['age']= df['age'].fillna(df['age'].mean())
df1['bmi']= df['bmi'].fillna(df['bmi'].mean())
df1['cholesterol']= df['cholesterol'].fillna(df['cholesterol'].mean())
df1['systolic_bp']= df['systolic_bp'].fillna(df['systolic_bp'].mean())
df1

     age    bmi  cholesterol  systolic_bp
79  40.0  30.30       214.00       108.30
58  21.0  26.50       209.80       122.10
5   27.0  23.90       227.80       117.20
19  72.0  22.90       168.10       108.18
93  59.0  26.78       143.60       110.20
25  21.0  30.30       192.66        83.10

In [74]:
df2 = df1.copy()

df2.iloc[0, 0] = np.nan

df2

     age    bmi  cholesterol  systolic_bp
79   NaN  30.30       214.00       108.30
58  21.0  26.50       209.80       122.10
5   27.0  23.90       227.80       117.20
19  72.0  22.90       168.10       108.18
93  59.0  26.78       143.60       110.20
25  21.0  30.30       192.66        83.10

In [75]:
X1 = df2.iloc[[1,2,3,4,5],1:]
X1

      bmi  cholesterol  systolic_bp
58  26.50       209.80       122.10
5   23.90       227.80       117.20
19  22.90       168.10       108.18
93  26.78       143.60       110.20
25  30.30       192.66        83.10

In [76]:
Y1 = df2.iloc[[1,2,3,4,5],0]
Y1

58    21.0
5     27.0
19    72.0
93    59.0
25    21.0
Name: age, dtype: float64

In [78]:
df2.iloc[0,1:]

bmi             30.3
cholesterol    214.0
systolic_bp    108.3
Name: 79, dtype: float64

In [79]:
Lr = LinearRegression()

Lr.fit(X1, Y1)

Y_pred = Lr.predict(df2.iloc[[0],1:].values.reshape(1,3))
Y_pred

C:\Users\lands\AppData\Roaming\Python\Python314\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([-0.76320715])

In [80]:
df2.iloc[[0],0] = -0.76

df2

      age    bmi  cholesterol  systolic_bp
79  -0.76  30.30       214.00       108.30
58  21.00  26.50       209.80       122.10
5   27.00  23.90       227.80       117.20
19  72.00  22.90       168.10       108.18
93  59.00  26.78       143.60       110.20
25  21.00  30.30       192.66        83.10

In [81]:
df2.iloc[4, 1] = np.nan

df2

      age   bmi  cholesterol  systolic_bp
79  -0.76  30.3       214.00       108.30
58  21.00  26.5       209.80       122.10
5   27.00  23.9       227.80       117.20
19  72.00  22.9       168.10       108.18
93  59.00   NaN       143.60       110.20
25  21.00  30.3       192.66        83.10

In [83]:
X2 = df2.iloc[[0, 1,2,3,5], [0,2,3]]
X2

      age  cholesterol  systolic_bp
79  -0.76       214.00       108.30
58  21.00       209.80       122.10
5   27.00       227.80       117.20
19  72.00       168.10       108.18
25  21.00       192.66        83.10

In [85]:
Y2 = df2.iloc[[0,1,2,3,5],1]
Y2

79    30.3
58    26.5
5     23.9
19    22.9
25    30.3
Name: bmi, dtype: float64

In [90]:
df2.iloc[[4],[0,2,3]]

     age  cholesterol  systolic_bp
93  59.0        143.6        110.2

In [91]:
Lr2 = LinearRegression()

Lr2.fit(X2, Y2)

Y_pred2 = Lr2.predict(df2.iloc[[4],[0,2,3]].values.reshape(1,3))
Y_pred2

C:\Users\lands\AppData\Roaming\Python\Python314\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([27.40793427])

In [92]:
df2.iloc[4,1] = 27.40

df2

      age   bmi  cholesterol  systolic_bp
79  -0.76  30.3       214.00       108.30
58  21.00  26.5       209.80       122.10
5   27.00  23.9       227.80       117.20
19  72.00  22.9       168.10       108.18
93  59.00  27.4       143.60       110.20
25  21.00  30.3       192.66        83.10

In [93]:
df2.iloc[5, 2] = np.nan

df2

      age   bmi  cholesterol  systolic_bp
79  -0.76  30.3        214.0       108.30
58  21.00  26.5        209.8       122.10
5   27.00  23.9        227.8       117.20
19  72.00  22.9        168.1       108.18
93  59.00  27.4        143.6       110.20
25  21.00  30.3          NaN        83.10

In [94]:
X3 = df2.iloc[0:5, [0,1,3]]
X3

      age   bmi  systolic_bp
79  -0.76  30.3       108.30
58  21.00  26.5       122.10
5   27.00  23.9       117.20
19  72.00  22.9       108.18
93  59.00  27.4       110.20

In [100]:
Y3 = df2.iloc[0:5, 2]
Y3

79    214.0
58    209.8
5     227.8
19    168.1
93    143.6
Name: cholesterol, dtype: float64

In [101]:
df2.iloc[5, [0,1,3]]

age            21.0
bmi            30.3
systolic_bp    83.1
Name: 25, dtype: float64

In [102]:
Lr3 = LinearRegression()

Lr3.fit(X3, Y3)

Y_pred3 = Lr3.predict(df2.iloc[5, [0,1,3]].values.reshape(1,3))
Y_pred3

C:\Users\lands\AppData\Roaming\Python\Python314\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([189.67674912])

In [103]:
df2.iloc[5, 2] = 189.67
df2

      age   bmi  cholesterol  systolic_bp
79  -0.76  30.3       214.00       108.30
58  21.00  26.5       209.80       122.10
5   27.00  23.9       227.80       117.20
19  72.00  22.9       168.10       108.18
93  59.00  27.4       143.60       110.20
25  21.00  30.3       189.67        83.10

In [104]:
df2.iloc[[3], [3]] = np.nan
df2

      age   bmi  cholesterol  systolic_bp
79  -0.76  30.3       214.00        108.3
58  21.00  26.5       209.80        122.1
5   27.00  23.9       227.80        117.2
19  72.00  22.9       168.10          NaN
93  59.00  27.4       143.60        110.2
25  21.00  30.3       189.67         83.1

In [106]:
X4 = df2.iloc[[0,1,2,4,5], 0:3]
X4

      age   bmi  cholesterol
79  -0.76  30.3       214.00
58  21.00  26.5       209.80
5   27.00  23.9       227.80
93  59.00  27.4       143.60
25  21.00  30.3       189.67

In [107]:
Y4 = df2.iloc[[0,1,2,4,5], 3]
Y4

79    108.3
58    122.1
5     117.2
93    110.2
25     83.1
Name: systolic_bp, dtype: float64

In [108]:
df2.iloc[3, 0:3]

age             72.0
bmi             22.9
cholesterol    168.1
Name: 19, dtype: float64

In [111]:
Lr4 = LinearRegression()

Lr4.fit(X4, Y4)

Y_pred4 = Lr4.predict(df2.iloc[3, 0:3].values.reshape(1, 3))
Y_pred4

C:\Users\lands\AppData\Roaming\Python\Python314\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([107.49123524])

In [112]:
df2.iloc[[3], [3]] = 107.49
df2

      age   bmi  cholesterol  systolic_bp
79  -0.76  30.3       214.00       108.30
58  21.00  26.5       209.80       122.10
5   27.00  23.9       227.80       117.20
19  72.00  22.9       168.10       107.49
93  59.00  27.4       143.60       110.20
25  21.00  30.3       189.67        83.10

In [113]:
## After 1st iteration 

df2

      age   bmi  cholesterol  systolic_bp
79  -0.76  30.3       214.00       108.30
58  21.00  26.5       209.80       122.10
5   27.00  23.9       227.80       117.20
19  72.00  22.9       168.10       107.49
93  59.00  27.4       143.60       110.20
25  21.00  30.3       189.67        83.10

In [114]:
# substract iteration 0 from 1

df2 - df1

      age   bmi  cholesterol  systolic_bp
79 -40.76  0.00         0.00         0.00
58   0.00  0.00         0.00         0.00
5    0.00  0.00         0.00         0.00
19   0.00  0.00         0.00        -0.69
93   0.00  0.62         0.00         0.00
25   0.00  0.00        -2.99         0.00

### repeat all the steps again to obtain iteration 2  -- then substract iteration 1 from 2